// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osslayocaewmnudrszyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zc2xheW9jYWV3bW51ZHJzenl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODgxNTcsImV4cCI6MjA3MTM2NDE1N30.Y1xh23pVc4hrdQi9Jhx1LL3B1FVoha2bW69mAgul1j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});